name = "profilator"
main = "src/index.ts"
compatibility_date = "2026-05-01"
compatibility_flags = [ "nodejs_compat" ]
send_metrics = false

[assets]
directory = "./public"
binding = "ASSETS"

[[rules]]
type = "Text"
globs = [ "**/*.svg" ]
fallthrough = true
